related_terms:
  unlicensed spectrum:
    - unlicensed
    - licence exempt
    - license exempt
    - general user licence
    - general user licences
    - licence free
    - license free
    - shared spectrum
    - class licence
    - class licences
    - short range devices

  license exempt:
    - license exempt
    - licence exempt
    - unlicensed
    - unlicensed spectrum
    - general user licence
    - general user licences
    - licence free
    - license free
    - class licence
    - class licences
    - short range devices

  licence exempt:
    - licence exempt
    - license exempt
    - unlicensed
    - unlicensed spectrum
    - general user licence
    - general user licences
    - licence free
    - license free
    - class licence
    - class licences
    - short range devices
